version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    volumes:
      - ./src:/opt/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf

volumes:
  mongo_data:
