FROM python:3.11

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY requirements.txt /opt/app/

RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir

COPY . /opt/app/

RUN useradd -ms /bin/bash wiki
RUN chown -R wiki:wiki /opt/app

ADD scripts/docker-entrypoint-prod.sh /home/wiki/docker-entrypoint-prod.sh
ADD scripts/check_service.py /home/wiki/check_service.py

RUN chmod +x /home/wiki/docker-entrypoint-prod.sh
USER wiki

ENTRYPOINT ["/home/wiki/docker-entrypoint-prod.sh"]
